# Starship configuration with midnight blue and reddish-pink color scheme
# Time module at the end, username module removed, cmd_duration included
# Right side of the prompt made pointy with left-pointing separators

format = """
[](#1C2526)\
    $directory\
    [](fg:#1C2526 bg:#2E3A3C)\
    $git_branch\
    $git_status\
    [](fg:#2E3A3C bg:#FF5C8A)\
    $c\
    $elixir\
    $elm\
    $golang\
    $haskell\
    $java\
    $julia\
    $nodejs\
    $nim\
    $rust\
    [](fg:#FF5C8A bg:#D81B60)\
    $docker_context\
    [](fg:#D81B60)\
    """
    right_format = """
    [](fg:#B71C4C bg:#B71C4C)\
      $cmd_duration\
      [](fg:#1C2526 bg:#B71C4C)\
      $time\
      """

      command_timeout = 5000
      add_newline = false

      [directory]
      style = "bg:#1C2526"
      format = "[ $path ]($style)"
      truncation_length = 3
      truncation_symbol = "…/"

      [directory.substitutions]
      "Documents" = "󰈙 "
      "Downloads" = " "
      "Music" = " "
      "Pictures" = " "

      [c]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [docker_context]
      symbol = " "
      style = "bg:#D81B60"
      format = '[ $symbol $context ]($style) $path'

      [elixir]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [elm]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [git_branch]
      symbol = ""
      style = "bg:#2E3A3C"
      format = '[ $symbol $branch ]($style)'

      [git_status]
      style = "bg:#2E3A3C"
      format = '[$all_status$ahead_behind ]($style)'

      [golang]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [haskell]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [java]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [julia]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [nodejs]
      symbol = ""
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [nim]
      symbol = " "
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [python]
      style = "bg:#1C2526"
      format = '[(\($virtualenv\) )]($style)'

      [rust]
      symbol = ""
      style = "bg:#FF5C8A"
      format = '[ $symbol ($version) ]($style)'

      [time]
      disabled = false
      time_format = "%R"
      style = "bg:#1C2526"
      format = '[ $time ]($style)'

      [cmd_duration]
      min_time = 500
      style = "bg:#B71C4C"
      format = '[ ⏱ $duration ]($style)'
